version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: opm_php_app
    volumes:
      # Monta el c贸digo fuente de la aplicaci贸n
      - ./:/var/www/html
    networks:
      - app_network
    depends_on:
      - nginx

  nginx:
    image: nginx:latest
    container_name: opm_nginx_server
    ports:
      # Mapea el puerto 8085 en el host al puerto 80 del contenedor
      - "8085:80"
    volumes:
      # Configuraci贸n personalizada de Nginx
      - ./nginx:/etc/nginx/conf.d
      # Monta el c贸digo fuente para servirlo
      - ./:/var/www/html
    networks:
      - app_network

networks:
  app_network:
