<<<<<<< HEAD
version: '3.9'
=======
version: '3.8'
>>>>>>> 9d65d9a (instalacion de laravel en app_api)

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
<<<<<<< HEAD
    container_name: opm_php_app
    volumes:
      # Monta el c贸digo fuente de la aplicaci贸n
      - ./:/var/www/html
    networks:
      - app_network
    depends_on:
      - nginx

  nginx:
    image: nginx:latest
    container_name: opm_nginx_server
    ports:
      # Mapea el puerto 8085 en el host al puerto 80 del contenedor
      - "8085:80"
    volumes:
      # Configuraci贸n personalizada de Nginx
      - ./nginx:/etc/nginx/conf.d
      # Monta el c贸digo fuente para servirlo
      - ./:/var/www/html
    networks:
      - app_network

networks:
  app_network:
=======
    container_name: opm-laravel-app
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
      - ./php/php.ini:/usr/local/etc/php/php.ini
    networks:
      - opm-network
    depends_on:
      - db

  webserver:
    image: nginx:latest
    container_name: opm-laravel-web
    restart: unless-stopped
    ports:
      - "8088:80"
    volumes:
      - .:/var/www/html
      - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - opm-network
    depends_on:
      - app

  db:
    image: mysql:8.0
    container_name: opm-laravel-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_USER: laraveluser
      MYSQL_PASSWORD: laravelpass
      MYSQL_ROOT_PASSWORD: rootpass
    ports:
      - "3308:3306"
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - opm-network

networks:
  opm-network:

volumes:
  dbdata:
>>>>>>> 9d65d9a (instalacion de laravel en app_api)

