<?php
ini_set('display_errors', 1);
ini_set('display_startup_errors', 1);
error_reporting(E_ALL);
//ADAIA
$conn2 = oci_connect('WMS', 'wms123', '181.94.246.220:1521');
if (!$conn2) {
    $e = oci_error();
    trigger_error(htmlentities($e['message'], ENT_QUOTES), E_USER_ERROR);
}
$oci_qry = "SELECT ST_ARTICULOS.COD_ARTICULO,ST_ARTICULOS.COD_INT_ARTICULO,ST_ARTICULOS.DESCRIPCION,ST_ARTICULOS.COD_UNIDAD_MEDIDA,ST_ARTICULOS.IND_ROTACION_ART,ST_ARTICULOS.COD_BARRA_ART,ST_GRUPOS_ART.ABREVIATURA,ST_FAMILIA.DESCRIPCION,ST_TIPOS_ARTICULOS.DESCRIPCION
FROM ST_ARTICULOS,ST_GRUPOS_ART,ST_FAMILIA,ST_TIPOS_ARTICULOS
WHERE ST_ARTICULOS.COD_GRUPO_ART=ST_GRUPOS_ART.COD_GRUPO_ART
AND ST_FAMILIA.COD_FAMILIA=ST_ARTICULOS.COD_FAMILIA
AND ST_ARTICULOS.COD_TIP_ART=ST_TIPOS_ARTICULOS.COD_TIP_ARTICULO  and ROWNUM <= 10";
//echo $oci_qry;
$dt = oci_parse($conn2, $oci_qry);
oci_execute($dt);
while($row = oci_fetch_array($dt, OCI_ASSOC+OCI_RETURN_NULLS)){
    var_dump($row);
}